myproc:test.c
	gcc -o $@ $^
#myproc:test.o
#	gcc -o $@ $^
#test.o:test.s
#	gcc -c -o $@ $^
#tset.s:test.i
#	gcc -S -o $@ $^
#test.i:test.c
#	gcc -E -o $@ $^

.PHONY:clean
clean:
	rm -rf *.i *.o *.s myproc
